### ISSUE TITLE
Unable to start NETworkManager

### ISSUE THREAD

**Issue by egnirra** [BornToBeRoot/NETworkManager#83] opened 2018-04-23 12:54 UTC
**Describe your issue or feature request**:
Program crashes before it starts/shows anything on screen.
Had to check event logs before i knew what was going on.

**Steps to reproduce the issue**:

1. Download latest release
2. Start NETworkManager.exe
3. Nothing happens

**NETworkManager version**: 1.6.0.0

**Windows version**: 10 pro

**.NET-Framework version**: .NET Framework 4.7.1 release 461308

**Screenshots**
![image](https://user-images.githubusercontent.com/37709886/39127648-e7b4daa2-4705-11e8-8c40-f0e31aa090e7.png)
![image](https://user-images.githubusercontent.com/37709886/39127652-ea670afe-4705-11e8-976a-0decbc76a388.png)

<details>
<summary>Application: NETworkManager.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at NETworkManager.ViewModels.NetworkInterfaceViewModel.set_SelectedNetworkInterface(NETworkManager.Models.Network.NetworkInterfaceInfo)
   at NETworkManager.ViewModels.NetworkInterfaceViewModel+<LoadNetworkInterfaces>d__160.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at NETworkManager.App.Main()

--------------------------------------------------------------------------------------------------

Faulting application name: NETworkManager.exe, version: 1.6.0.0, time stamp: 0x5adc0a1e
Faulting module name: KERNELBASE.dll, version: 10.0.16299.371, time stamp: 0xee297154
Exception code: 0xe0434352
Fault offset: 0x00103ef2
Faulting process id: 0x774
Faulting application start time: 0x01d3db00de1c411e
Faulting application path: C:\Users\thomas.arringe\Downloads\NETworkManager_v1.6.0.0\NETworkManager\NETworkManager.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 881ab1ea-f819-4d20-b37d-883e165abe09
Faulting package full name: 
Faulting package-relative application ID: 
</summary>

</details>

**Comment by BornToBeRoot** [comment] 2018-04-23 13:48
Can you post me screenshot from your network adapters in windows?

I got another report via Reddit, but i can't reproduce.

**Comment by egnirra** [comment] 2018-04-23 14:01
Sure.

![image](https://user-images.githubusercontent.com/37709886/39131370-8c25a414-470f-11e8-9341-f4cef92b8276.png)
![image](https://user-images.githubusercontent.com/37709886/39131374-8e1c85e4-470f-11e8-9c1f-6750c45d7f2b.png)

**Comment by deaquino** [comment] 2018-04-23 14:09
I attach mine, I have the same issue.

![image](https://user-images.githubusercontent.com/1284884/39131801-9d4c4c38-4710-11e8-9f6a-473716e8f5b5.png)

**Comment by BornToBeRoot** [comment] 2018-04-23 22:47
I installed some of these tools to add network interfaces to my virtual machine, but without success... i still can't reproduce.
The execption is thrown when selecting a network interface on start, but i don't know in which line / property. 

I changed the version here, that the error is intercepted and one or two MessageBoxes are displayed.
Just open the NETworkManager.exe and you should see a MessageBox. 

[NETworkManager_v1.6.0.0_DEBUG.zip](https://github.com/BornToBeRoot/NETworkManager/files/1940258/NETworkManager_v1.6.0.0_DEBUG.zip)



Maybe someone with the problem has installed Visual Studio 2017 and could also debug it ?!

**Comment by deaquino** [comment] 2018-04-24 06:46
I'll try it in few hours.
Thanks

**Comment by egnirra** [comment] 2018-04-24 06:50
The debug version starts for me.. strange.
The normal version does not work still.

![image](https://user-images.githubusercontent.com/37709886/39170649-937f14ce-479c-11e8-9923-caffa532ddc0.png)

**Comment by BornToBeRoot** [comment] 2018-04-24 06:58
Indeed strange...

Does it show a MessageBox?

**Comment by egnirra** [comment] 2018-04-24 07:00
No i didn't get anything :/ I can test more after I get home from work, I'll test on my laptop also.

**Comment by egnirra** [comment] 2018-04-24 07:55
It seems to work fine on my laptop, I'll test more when i get home.
![image](https://user-images.githubusercontent.com/37709886/39173618-8e2eca9c-47a5-11e8-948a-570cde47b29c.png)

**Comment by deaquino** [comment] 2018-04-24 11:58
![debug-error-01](https://user-images.githubusercontent.com/1284884/39185445-74075432-47c7-11e8-9d05-437d5ad0dad9.PNG)
![debug-error-02](https://user-images.githubusercontent.com/1284884/39185446-744cfbf4-47c7-11e8-89af-b46d68ccfc32.PNG)

It´s in Spanish...

**Comment by deaquino** [comment] 2018-04-24 12:06
value.IPv4Gateway is not null but it´s an empty collection, so value.IPv4Gateway.FirstOrDefault() throws an exception.

![image](https://user-images.githubusercontent.com/1284884/39185933-2e216474-47c9-11e8-8eb6-b78af978dd15.png)

**Comment by egnirra** [comment] 2018-04-24 12:18
It must be possible to set a default value if it's empty then? :)

**Comment by deaquino** [comment] 2018-04-24 12:31
Fixed here: #86

**Comment by BornToBeRoot** [comment] 2018-04-24 13:30
Yep. Line 164...

@deaquino thanks!

**Comment by BornToBeRoot** [comment] 2018-04-24 13:39
#86 merged.

I will release a new version in a few days, with some bugfixes.

**Closed as completed by BornToBeRoot** 2018-04-24 13:39 UTC
Labels: :bug: bug
