### ISSUE TITLE
Ping-Monitor - Group by "Profile-Groups"

### ISSUE THREAD

**Issue by nhwCoder** [BornToBeRoot/NETworkManager#2643] opened 2024-03-14 18:15 UTC
Please add to `Ping-Monitor` in settings the possibility to **group by "Profile-Groups"**.
VERY helpful if someone has a lot of host entries.

**Comment by BornToBeRoot** [comment] 2024-03-14 19:20
Duplicate of https://github.com/BornToBeRoot/NETworkManager/issues/2566

I am not yet sure how to implement it, but starting with a simple group by profile-groups would be ok. I can add statistics later.

**Comment by BornToBeRoot** [comment] 2024-03-14 21:05
Something like this (basic grouping + close/remove all hosts in group):

![image](https://github.com/BornToBeRoot/NETworkManager/assets/16019165/18f95e88-5d7f-4525-ade3-bc493a885d1b)

![image](https://github.com/BornToBeRoot/NETworkManager/assets/16019165/0b7ea269-3858-42fe-979d-d73035daae08)

**Comment by BornToBeRoot** [comment] 2024-03-14 21:06
![image](https://github.com/BornToBeRoot/NETworkManager/assets/16019165/737ba6f5-daf3-4f0a-84a0-f75d5e4ebcf9)

**Comment by BornToBeRoot** [comment] 2024-03-14 21:25
Done via #2645 - will be in the next release!

**Closed as completed** 2024-03-14 21:37 UTC
Labels: :rocket: feature-request

**Comment by nhwCoder** [comment] 2024-03-14 22:13
Hi,

GREAT! Exactly what I was looking for!

Vielen Dank & Gruß aus AT

PS: In fact having this feature based on "Tags" would give us even greatest flexibility.

PSS: Looking forward for a fast next release :-)
