### ISSUE TITLE
ipscanner & portscanner do not work

### ISSUE THREAD

**Issue by NeoFax75** [BornToBeRoot/NETworkManager#2794] opened 2024-07-19 23:23 UTC
**Describe your issue**: Click on IP Scan or Port Scan and the app does nothing

**Steps to reproduce the issue**:

1. Open app.
2. Click on IP scan.
3. Go to market for 1 hour and the app does nothing. It doesn't even show the subscreen to select the ip range

**NETworkManager version**: 2024.6.15.0

- [ ] Portable

**Windows version** (like 10.0.x.x): 11 22635.3930

**.NET version** (like 6.0.x): .NET 8

**Screenshots**

<details>
<summary>Eventlog (if application crashes)</summary>

</details>

**Comment by BornToBeRoot** [comment] 2024-07-21 21:22
What IP Range / Port range do you enter for the scan? Is there any crash log?

`%localappdata%\NETworkManager\NETworkmanager.log`

Is there any progress bar visible?

![image](https://github.com/user-attachments/assets/0baca6f0-6e44-4a14-8dc2-5013719b3d13)

**Comment by TechInterMezzo** [comment] 2024-08-15 09:03
I have the same problem, but I don't see errors in the log.
It's not only IP or Port Scanner. There are also other menu options that do nothing when I click on them. It's stuck on the last working page. For example Ping Monitor works and the page does not change when I click on IP Scanner.

```
2024-08-15 10:58:48,920 [1] INFO  NETworkManager.App - Application settings are being loaded...
2024-08-15 10:58:49,092 [1] INFO  NETworkManager.App - Application settings are on version 2023.11.28.0 and will be upgraded to 2024.6.15.0
2024-08-15 10:58:49,093 [1] INFO  NETworkManager.Settings.SettingsManager - Start settings upgrade from 2023.11.28.0 to 2024.6.15.0...
2024-08-15 10:58:49,093 [1] INFO  NETworkManager.Settings.SettingsManager - Apply upgrade to 2024.6.15.0...
2024-08-15 10:58:49,106 [1] INFO  NETworkManager.Settings.SettingsManager - Settings upgrade finished!
2024-08-15 10:58:49,106 [1] INFO  NETworkManager.App - Application settings upgraded to version 2024.6.15.0
2024-08-15 10:58:49,107 [1] INFO  NETworkManager.App - Application localization culture has been set to de-DE (Settings value is "").
2024-08-15 10:58:49,107 [1] INFO  NETworkManager.App - Try to acquire mutex with GUID 6A3F34B2-161F-4F70-A8BC-A19C40F79CFB for single instance detection...
2024-08-15 10:58:49,107 [1] INFO  NETworkManager.App - Mutex value for 6A3F34B2-161F-4F70-A8BC-A19C40F79CFB is True
2024-08-15 10:58:49,107 [1] INFO  NETworkManager.App - Setup background job with interval 5 minute(s)...
2024-08-15 10:58:49,108 [1] INFO  NETworkManager.App - ThreadPool min threads set to: workerThreads: 520, completionPortThreads: 513
2024-08-15 10:58:49,108 [1] INFO  NETworkManager.App - Show SplashScreen while application is loading...
2024-08-15 10:58:49,131 [1] INFO  NETworkManager.App - Set StartupUri to MainWindow.xaml...
2024-08-15 10:58:49,845 [1] INFO  NETworkManager.MainWindow - Configure application DNS...
2024-08-15 10:58:49,845 [1] INFO  NETworkManager.MainWindow - Use Windows DNS servers...
2024-08-15 10:59:08,277 [1] INFO  NETworkManager.App - Exiting NETworkManager...
2024-08-15 10:59:08,277 [1] INFO  NETworkManager.App - Stop background job (if it exists)...
2024-08-15 10:59:08,277 [1] INFO  NETworkManager.App - Save application settings...
2024-08-15 10:59:08,280 [1] INFO  NETworkManager.App - Bye!
2024-08-15 10:59:11,286 [1] INFO  NETworkManager.App - 
```

**Comment by TechInterMezzo** [comment] 2024-08-15 09:05
The newest pre release 2024.8.1.0 is working again. But 2024.6.15.0 did not work.

**Comment by BornToBeRoot** [comment] 2024-11-10 23:57
Closed for now, as I cannot reproduce it. Maybe this was fixed in a patch of a library with a newer version.

Feel free to open it again if you have the problem again / can reproduce it

**Closed as completed by BornToBeRoot** 2024-11-10 23:57 UTC
Labels: :mag: needs triage
